
# rename this file to .tmux.conf and place at ~/.tmux.conf
# edit nano ~/.config/lxsession/LXDE-pi/autostart
# add this line ' @lxterminal -e tmux start-server '
# command 1st 3 line with '#' 
new-session -d
source-file /home/pi/GUIraspberrypi/tmux_sgo_conf.conf
